pipelines:
  buildAndTest:
    group: spring
    materials:
      mygit:
        git: https://github.com/mlucchini/spring-playground
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: ./gradlew
                   arguments:
                    - 'build'
