pipelines:
  buildAndTest:
    group: simple
    materials:
      mygit:
        git: https://github.com/mlucchini/spring-playground
    stages:
      - build:
          jobs:
            build:
              environment_variables:
                GRADLE_OPTS: "-Xmx64m -Dorg.gradle.jvmargs='-Xmx512m -XX:MaxPermSize=128m'"
              tasks:
               - exec:
                   command: bash
                   arguments:
                    - '-c'
                    - 'docker run --rm --user $UID -v "$PWD":/project -w /project --name gradle gradle:alpine gradle build'
