version: '3'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_URI: "kafka:9092"
  kafka:
    image: spotify/kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
    ports:
      - "9092:9092"
      - "2181:2181"
